simulation:
  time_step_s: 30.0                     # integration step (s)
  duration_s:  2000.0                   # total simulated time (s)

  infrastructure_file: network.xml

  trains:
    - id: "train_1"
      kind: railml
      railml_file: output.xml
      formation_id: formation_class66_mk3
      timetable_train_id: "OT_Train1"
      environment:
        gradient: 0.01                  # rise/run (1 % uphill)
        wind_speed: 0.0
      driver:
        power_ratio: 0.8
        brake_ratio: 0.0

    - id: "train_2"
      kind: railml
      railml_file: output.xml
      formation_id: formation_class66_mk3
      timetable_train_id: "OT_Train2"
      environment:
        gradient: 0.0
        wind_speed: 5.0                 # m/s head-wind
      driver:
        power_ratio: 1.0
        brake_ratio: 0.0
